name: scroll_adapter
description: adaptable scroll view
version: 0.1.8-dev
author: liniec<liniec50@gmail.com>
homepage: https://github.com/Linies/scroll_adapter

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
